services:
  hermes:
    image: hermes:latest
    build: .
    labels:
      - "com.docker.compose.project=${STACK_NAME}"
    ports:
      - "8000:8000"
      - "2525:2525"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - EMAIL_SENDER
      - ENV
    networks:
      - aether-net
    restart: unless-stopped

networks:
  aether-net:
    external: true
