version: '3.8'

services:
  hermes:
    build: .
    container_name: hermes
    ports:
      - "8000:8000"
      - "2525:2525"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - EMAIL_SENDER
    networks:
      - aether-net
    restart: unless-stopped

networks:
  aether-net:
    external: true
