services:
  hermes:
    image: ${REGISTRY_PREFIX}hermes:${STACK_NAME:-latest}
    build: .
    labels:
      - "com.docker.compose.project=${STACK_NAME}"
    ports:
      - "8000:8000"
      - "2525:2525"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    environment:
      - AWS_REGION
      - EMAIL_SENDER
      - ENV
    networks:
      - aether-net
    secrets:
      - source: hermes_aws_access_key_id
        target: AWS_ACCESS_KEY_ID
      - source: hermes_aws_secret_access_key
        target: AWS_SECRET_ACCESS_KEY
    restart: unless-stopped

secrets:
  hermes_aws_access_key_id:
    external: true
    name: ${HERMES_AWS_ACCESS_KEY_ID_NAME}
  hermes_aws_secret_access_key:
    external: true
    name: ${HERMES_AWS_SECRET_ACCESS_KEY_NAME}

networks:
  aether-net:
    external: true
